### ISSUE TITLE
Example files

### ISSUE THREAD

**Issue by renatovargas** [mivanic/tabloToR#1]
Congratulations on the publication of the Article in the Journal of Global Economic Analysis. The community highly appreciate your efforts. I am trying to follow the example in the README of this repository, which is the one in the paper as well and, just as the paper explains regarding aggregation tools, the files I got from GTAP are different than the example: 

tstrade.har
BASEDATA.har
BaseRate.har
BaseView.har
co2.har
default.agg
default.prm
gsdvole.har
GTAPSAM.har
metadata.har
SETS.har

Would it be possible to add a #comment to understand which files go with which: gtapsets = HARr::read_har('gsdgset.har'),gtapparm = HARr::read_har('gsdgpar.har'),gtapdata = HARr::read_har('gsdgdat.har') just so I can replicate the example from this documentation? 

I assume gtapsets is SETS.har and gtapdata is BASEDATA.har, but I'm at a loss with gtapparm and the example is stuck. 

I am using GTAP 9 instead of 11, because it's free and the 6.2 model used in the paper.

Thanks in advance!!

**Comment by MarosIvanic-USDA** [comment]
Thank you! The quick answer is that gtapparam = default.prm--thses are the model parameters. I have added this to readme.md
